import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Inter,
  Montserrat,
  Montserrat_Alternates,
  Bricolage_Grotesque,
} from 'next/font/google';
import NavBar from '@/components/NavBar';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const montAlt = Montserrat_Alternates({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-mont-alt',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
  variable: '--font-inter',
});

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  weight: '300',
  display: 'swap',
  variable: '--font-bricolage',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montAlt.variable} ${montserrat.variable} ${inter.variable} ${bricolage.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
